// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_uou705gjlzX49KzK5rpgLS3yrs7pPCY',
    appId: '1:264780488100:web:bcb164b36428703960f531',
    messagingSenderId: '264780488100',
    projectId: 'prototipodavid-4fe2c',
    authDomain: 'prototipodavid-4fe2c.firebaseapp.com',
    storageBucket: 'prototipodavid-4fe2c.firebasestorage.app',
    measurementId: 'G-W8SJFTH4BL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARC-Av87ClJVHi1aPNiibQte4aa9WBv1Y',
    appId: '1:264780488100:android:82addbfbf7fc7b6e60f531',
    messagingSenderId: '264780488100',
    projectId: 'prototipodavid-4fe2c',
    storageBucket: 'prototipodavid-4fe2c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSlR3VfH7dj7OemSJFBD8cU1t1y8M5xXY',
    appId: '1:264780488100:ios:887caf961b1dfafa60f531',
    messagingSenderId: '264780488100',
    projectId: 'prototipodavid-4fe2c',
    storageBucket: 'prototipodavid-4fe2c.firebasestorage.app',
    iosClientId: '264780488100-ok63udl9p3k2q1mqdivbsigkeihprh4u.apps.googleusercontent.com',
    iosBundleId: 'com.example.prototipodavid',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCSlR3VfH7dj7OemSJFBD8cU1t1y8M5xXY',
    appId: '1:264780488100:ios:887caf961b1dfafa60f531',
    messagingSenderId: '264780488100',
    projectId: 'prototipodavid-4fe2c',
    storageBucket: 'prototipodavid-4fe2c.firebasestorage.app',
    iosClientId: '264780488100-ok63udl9p3k2q1mqdivbsigkeihprh4u.apps.googleusercontent.com',
    iosBundleId: 'com.example.prototipodavid',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB_uou705gjlzX49KzK5rpgLS3yrs7pPCY',
    appId: '1:264780488100:web:0ab308f0e6654ede60f531',
    messagingSenderId: '264780488100',
    projectId: 'prototipodavid-4fe2c',
    authDomain: 'prototipodavid-4fe2c.firebaseapp.com',
    storageBucket: 'prototipodavid-4fe2c.firebasestorage.app',
    measurementId: 'G-RPDRLZFVLS',
  );

}