name: Build Flutter APK

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - master

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar código
        uses: actions/checkout@v4

      - name: Instalar Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Instalar Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true

      - name: Ver versión Flutter
        run: flutter --version

      - name: Instalar dependencias
        run: flutter pub get

      - name: Analizar proyecto
        run: flutter analyze
        continue-on-error: true

      - name: Compilar APK debug
        run: flutter build apk --debug

      - name: Subir APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug-apk
          path: build/app/outputs/flutter-apk/app-debug.apk
